### ISSUE TITLE
Boost.Random uses deprecated boost/pending/integer_log2.hpp

### ISSUE THREAD

**Issue by dscharrer** [boostorg/random#49]
$ printf "#include <boost/random/mersenne_twister.hpp>\n" | gcc -c -x c++ - -o /dev/null -I ~/pro/build/deps/boost-git/
    In file included from /home/dscharrer/pro/build/deps/boost-git/boost/random/detail/integer_log2.hpp:19,
                     from /home/dscharrer/pro/build/deps/boost-git/boost/random/detail/large_arithmetic.hpp:19,
                     from /home/dscharrer/pro/build/deps/boost-git/boost/random/detail/const_mod.hpp:23,
                     from /home/dscharrer/pro/build/deps/boost-git/boost/random/detail/seed_impl.hpp:26,
                     from /home/dscharrer/pro/build/deps/boost-git/boost/random/mersenne_twister.hpp:30,
                     from <stdin>:1:
    /home/dscharrer/pro/build/deps/boost-git/boost/pending/integer_log2.hpp:7:59: note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.
     BOOST_HEADER_DEPRECATED("<boost/integer/integer_log2.hpp>");
                                                               ^

**Comment by kersson** [comment]
This is fixed on `develop` by d217e56535816d6b9d662638674939ef205c57e4, but is unfortunately in [1.69.0](https://github.com/boostorg/random/tree/boost-1.69.0). Do we have to live with these annoying messages until 1.70.0?

**Comment by pbertoni** [comment]
@kersson what about prepending
```
#define BOOST_PENDING_INTEGER_LOG2_HPP
#include <boost/integer/integer_log2.hpp>
```
to your offending header inclusion, instead of being choosy ?

**Comment by kersson** [comment]
Thanks for the suggestion @pbertoni. We get these warnings in a number of source files, so we opted to use `BOOST_ALLOW_DEPRECATED_HEADERS` for now.

**Comment by dscharrer** [comment]
As mentioned by @kersson this has been fixed for Boost 1.70 and there are workarounds to suppress the warnings in 1.69 so I consider this fixed.

**Comment by NewCTwo** [comment]
Hey, I'm having trouble compiling Caffe (using cmake) with this exact error:

    [ 32%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_im2col.cu.o
    Scanning dependencies of target caffe
    [ 34%] Building CXX object src/caffe/CMakeFiles/caffe.dir/blob.cpp.o
    [ 34%] Building CXX object src/caffe/CMakeFiles/caffe.dir/common.cpp.o
    In file included from /usr/include/boost/random/detail/integer_log2.hpp:19:0,
                     from /usr/include/boost/random/detail/large_arithmetic.hpp:19,
                     from /usr/include/boost/random/detail/const_mod.hpp:23,
                     from /usr/include/boost/random/detail/seed_impl.hpp:26,
                     from /usr/include/boost/random/mersenne_twister.hpp:30,
                     from /home/me/Packages/caffe/include/caffe/util/rng.hpp:7,
                     from /home/me/Packages/caffe/src/caffe/common.cpp:8:
    /usr/include/boost/pending/integer_log2.hpp:7:89: note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.
     BOOST_HEADER_DEPRECATED("<boost/integer/integer_log2.hpp>");
                                                                                             ^
    /home/me/Packages/caffe/src/caffe/common.cpp: In function ‘void caffe::GlobalInit(int*, char***)’:
    /home/me/Packages/caffe/src/caffe/common.cpp:45:5: error: ‘::gflags’ has not been declared
       ::gflags::ParseCommandLineFlags(pargc, pargv, true);
         ^
    src/caffe/CMakeFiles/caffe.dir/build.make:527: recipe for target 'src/caffe/CMakeFiles/caffe.dir/common.cpp.o' failed
    make[2]: *** [src/caffe/CMakeFiles/caffe.dir/common.cpp.o] Error 1
    CMakeFiles/Makefile2:267: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
    make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
    Makefile:129: recipe for target 'all' failed
    make: *** [all] Error 2
     

How do I enable `BOOST_ALLOW_DEPRECATED_HEADERS` as @kersson suggested?

**Comment by patrick-fromberg** [comment]
How is this closed? We are now more than a year later at version 1.74.0 and `null_output_iterator.hpp` still includes `boost/function_output_iterator.hpp` instead of `boost/iterator/function_output_iterator.hpp`.
